Repository DangsanFamily/Gurumi, pull requests merged in 2022-08, with the labels that each got.

#13 block 관련 기본 api 를 만든다
  backend/src/main/java/io/gurumi/core/blocks/domain/Block.java
  backend/src/main/java/io/gurumi/core/blocks/service/BlockService.java
  backend/src/main/java/io/gurumi/core/blocks/ui/BlockController.java
  backend/src/main/java/io/gurumi/core/blocks/ui/dto/BlockRequest.java
  backend/src/main/java/io/gurumi/core/blocks/ui/dto/BlockResponse.java
  backend/src/main/java/io/gurumi/core/blocks/ui/empty.txt
  backend/src/main/java/io/gurumi/core/letters/domain/Letter.java
Labels: 💽 백엔드, 🚀 기능, 🏗 리팩토링

#14 Feature/frontend/image block
  frontend/src/Components/ImageModal/ImageModal.js
  frontend/src/Components/ImageModal/style.css
  frontend/src/Components/LinkModal/LinkModal.js
  frontend/src/Components/LinkModal/style.css
  frontend/src/Components/MainModal/MainModal.js
  frontend/src/Components/MessageModal/MessageModal.js
  frontend/src/Components/MessageReviseModal/MessageReviseModal.js
  frontend/src/Page/CreateMessagePage/index.js
Labels: 💄 프론트엔드, 🚀 기능

#16 프론트엔드에서 Block관련 API를 테스트 성공하였다
  frontend/package.json
  frontend/src/Components/MainModal/MainModal.js
  frontend/src/Components/MessageModal/MessageModal.js
  frontend/src/Components/MessageReviseModal/MessageReviseModal.js
  frontend/src/Page/CreateMessagePage/index.js
Labels: 💄 프론트엔드, 🚀 기능

#20 make api for url info
  backend/build.gradle
  backend/src/main/java/io/gurumi/core/blocks/service/OpenGraphService.java
  backend/src/main/java/io/gurumi/core/blocks/ui/UrlInfoController.java
  backend/src/main/java/io/gurumi/core/blocks/ui/dto/UrlInfoResponse.java
Labels: 💽 백엔드, 🚀 기능

#23 AWS EC2 인스턴스를 사용하여 프로젝트를 배포한다
  .gitignore
  infra/nginx.sh
  infra/spring.sh
  infra/test.txt
Labels: ⚙️ 인프라

#29 Terraform 을 사용하여 사용하는 aws 리소스를 기록한다
  .gitignore
  infra/.gitignore
  infra/main.tf
Labels: ⚙️ 인프라
